### ISSUE TITLE
Flesh out project README

### ISSUE THREAD

**Issue by benbalter** [BenKallos/legislation#3]
The project has [a readme file](https://github.com/BenKallos/legislation/blob/master/README.md), but it doesn't do much to provide context to visitors to the repository. A few common questions to consider answering:
1. What is this? Why does it exist?
2. Why GitHub? What are the goals of putting it here, rather than e.g., a PDF?
3. I have feedback. Should I open an issue? A pull request? (What's the difference between the two?)
4. I have a proposed change. I've never used GitHub before. How do I submit it? Will you accept it?
5. Where can I see ongoing discussions regarding the proposed legislation?
6. Have these bills already passed? Already been proposed? What is the status of the project in relation to the legislative process?
7. Are these documents law? You just merged my pull request, that means I can do X, right?

**Comment by BenKallos** [comment]
Thank you for the numerous issues that you've posted @benbalter. My main reason for creating the repository was to harness and empower the community. Would encourage you to pull the README and modify it with answers that you may already know such #2, #3, #4, and #5. 

As for #6 & #7, legislation is a proposal for a law and by definition is not a law. To the extent that certain bills have become laws, we will do our best and welcome support from the community to keep this repository up to date while we wait on rules I helped pass to make legislation available through an open API.
